### ISSUE TITLE
`--directory` argument do not work in controller creation

### ISSUE THREAD

**Issue by blckshrk** [phalcon/phalcon-devtools#273]
Hi,

I think the `--directory` argument do not work. Actually, I try this : 

```
phalcon controller test --directory="app/controllers"
```

or this

```
phalcon controller test "app/controllers"
```

and I always get : 

```
Error: Please specify a controller directory 
```

The only solution I found is to define a `controllersDir` in `app\config\config.ini`.

Any clue ?
Thanks!

**Comment by sergeyklay** [comment]
Fixed

**Comment by sasa-b** [comment]
I get this error in multi module applications, using Phalcon 3? I can't find anything on the internet for my specific use case.

**Comment by sergeyklay** [comment]
Did you used the 3.2.x branch?

**Comment by sasa-b** [comment]
No I used the 3.1.2, but I tried the 3.2.0 ALPHA 1 still does not work.

This is my config 
` 'application' => [
        'appDir'         => APP_PATH. '/',
        'migrationsDir'  => APP_PATH. '/migrations/',
        'pluginsDir'     => APP_PATH. '/plugins/',
        'modelsDir'      => APP_PATH. '/Models/',
        'libraryDir'     => APP_PATH. '/Library/',
        'cacheDir'       => BASE_PATH . '/cache/',
        'baseUri'        => '/',
    ],
    'backend' => [
        'root'           => APP_PATH. '/Backend/',
        'namespace' => 'Backend\\Controllers\\',
        'controllersDir' => APP_PATH. '/Backend/Controllers/',
        'viewsDir'       => APP_PATH. '/Backend/Views/',
        'formsDir'       => APP_PATH. '/Backend/Forms/',
    ],
    'frontend' => [
        'root'           => APP_PATH. '/Frontend/',
        'namespace' => 'Frontend\\Controllers\\',
        'controllersDir' => APP_PATH. '/Frontend/Controllers/',
        'viewsDir'       => APP_PATH. '/Frontend/Views/',
        'formsDir'       => APP_PATH. '/Frontend/Forms/',
    ]`

**Comment by sergeyklay** [comment]
@sergeysviridenko Could you please take a look

**Comment by sergeysviridenko** [comment]
@sasa-b, could you show your steps

**Comment by sasa-b** [comment]
you have my config above, when I type the `phalcon controller Name` without a directory path param, I get this error 

>  Error: Please specify a controller directory.

because it is a multi module app and every module has it's own controllers directory

When I run the command with the directory param I get this error 

> This command should be invoked inside a Phalcon project directory. 
Even if I provide the base path

Here is the link to my repo you can clone it to reproduce https://github.com/sasa-b/phalcon-boiler

**Comment by sergeysviridenko** [comment]
In a multi module project you should use param '--output' for creation the controller. Param '--directory' using when the command running from not a project folder. 

For example:
if you are in a project directory run:
`phalcon controller --name=testContr --output=app/Backend/Controllers`. 
This command creates 'TestContrController.php' in '/your_project/app/Backend/Controllers'

**Comment by sasa-b** [comment]
That's it, thank you very much :)
